# Generated by Django 5.2.13 on 2026-05-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='game',
            field=models.CharField(choices=[('slots', 'Slots'), ('blackjack', 'Blackjack')], max_length=20),
        ),
    ]
